### ISSUE TITLE
Requests to GetBible V2 API fail due to CORS issue

### ISSUE THREAD

**Issue by dsuppiger** [renehamburger/blinx.js#107]
Upon loading blinx.js the request to the getbible checksum API fails with the following CORS error (Chrome):

`
Access to XMLHttpRequest at 'https://getbible.net/v2/checksum.json?v=1695667014779' from origin 'https://www.evangelium21.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

I assume this error was introduced with the migration to the V2 API.

Strangely when I load the checksum API directly in the Browser I can see that it does indeed respond with a `Access-Control-Allow-Origin: *` header.

**Comment by renehamburger** [comment]
Thanks for reporting the issue, @dsuppiger! This is a (newly introduced) issue in the getbible.net server, which I posted [here](https://git.vdm.dev/getBible/support/issues/9).

**Comment by renehamburger** [comment]
@dsuppiger, this has been fixed in v0.5.3. When you move to this version, also check out the breaking changes in [v0.5.1](https://github.com/renehamburger/blinx.js/releases/tag/v0.5.1).

**Comment by dsuppiger** [comment]
Thanks for the quick response Rene!
