### ISSUE TITLE
cdn.polyfill.io was taken down

### ISSUE THREAD

**Issue by benasocj** [renehamburger/blinx.js#112]
It seems that https://cdn.polyfill.io was taken down by its domain registrar as mentioned in many articles online such as [here](https://sansec.io/research/polyfill-supply-chain-attack) due to abuse.

It seems that for this reason, blinx.js is not working anymore.

The linked article above shares alternatives such as https://cdnjs.cloudflare.com/polyfill. Could you please update blinx.js accordingly?

**Comment by renehamburger** [comment]
Thanks for reporting this, @benasocj! I saw the news on cdn.polyfill.io, but I didn't remember that blinx.js is also using it.

By the way, if either of you, @benasocj or @n4bb12,  happen to know someone who is interested in becoming a maintainer of this project, let me know. I haven't been able to spend any considerable amount of time on it for years now, even though I still think it's really worth while!

**Comment by benasocj** [comment]
> happen to know someone who is interested in becoming a maintainer of this project, let me know

Unfortunately, I can't think of anyone at this stage. However, as a first step you could add a note at the top in `README.md`, mentioning that this project is looking for a new maintainer and linking them to a corresponding issue where this can be further discussed.
