### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by renehamburger** [renehamburger/blinx.js#25]
In the string 'Josua, Richter, 1. und 2. Samuel und 1. und 2. Könige', both 'Richter, 1' and 'Samuel und 1' are wrongly interpreted as references.

**Comment by dsuppiger** [comment]
Also references not specifying a book (e.g. 9,3) are referenced and default to the book of Romans.

**Comment by renehamburger** [comment]
This is actually a feature not a bug, @dsuppiger. :) Partial references that either contain a chapter and a verse or that contain recognised words like 'chapter' or 'verse' will be parsed based on the book and/or chapter of the previous passage. If '9,3' is not meant to be a Bible reference, you can skip it with `bx-skip` and if you want to provide another context than 'Romans' use `bx-context`. See [usage](https://github.com/renehamburger/blinx.js#usage) for more details.

**Comment by Boddlnagg** [comment]
We have a false positive on https://www.evangelium21.net/ressourcen/suche-jesum-und-sein-licht:
In the sentence "Am 8. Oktober 1867 heiratete er" the part "Am 8." is interpreted as a reference to Amos 8, and even a second occurrence of the same pattern "am 7. Februar". That is quite unfortunate.

We can work around it with `bx-skip`, but it seems to me that this pattern might occur more often in the German language and an exception for "Amos" might be a good idea.

**Comment by Boddlnagg** [comment]
Vorschlag: `Am N.` für eine Zahl `N` sollte immer als Ausnahme behandelt werden und nicht als Bibelstelle erkannt werden.

**Comment by renehamburger** [comment]
Yes, you're right, Patrick! I'll see if I can adjust that. This would usually need to be done upstream in the parser, but that project isn't barely maintained any more. I'll add that to blinx.js as a correction.

In the meantime you can surround the false positive by one of the default [blacklist selectors](https://github.com/renehamburger/blinx.js#usage): `<bx-skip>` or `.bx-skip` to avoid it being converted to a link.

By the way, PRs are always welcome! :)

**Comment by renehamburger** [comment]
@Boddlnagg, please try out the latest version. German dates prefixed with "am" should now longer be recognised as references from Amos.

**Comment by Boddlnagg** [comment]
What "latest" version? The git master? There is not yet a released version with the fix, right?

**Comment by renehamburger** [comment]
Oh, yes, sorry. Forgot to release it. It's released as v0.3.15 now.

**Comment by Boddlnagg** [comment]
Thanks, looks like it works correctly 👍
