### ISSUE TITLE
GetBible-API Update to v2

### ISSUE THREAD

**Issue by Metanoia23** [renehamburger/blinx.js#84]
Wie in der Readme von GetBible aufgelistet, wird der alte API-Aufruf nicht mehr unterstützt, sollte eigentlich schon Ende 2021 abgeschalten werden.

Jetzt sollte man den Pfad über `/v2` aufrufen.

https://github.com/getbible/v2

```
We will keep the old API (the current URL query option on getBible.net) active for another year, ending 2021. We therefore encourage you all to upgrade to the newer, better option, explained below, as soon as you can.

We will always have a Version one (V1) and a Version two ([V2](https://github.com/getbible/v2)) as long as the Lord permits. V1 will return the Holy Scripture in the same format as the original (old API) but with a whole new URL query format, which we will explain in details below. [V2](https://github.com/getbible/v2) will serve as the new format being introduced to solve common issues and provide a better, faster, stronger, more accurate, and convenient API of the Holy Scripture.
How will this work?

The old API query looked like this:

    https://getbible.net/json?passage=1Jn3

The new API (V1) query will look like this:

    https://getbible.net/v1/kjv/62/3.json

    That is really the only change, but we trust it will serve us all better.

[V2](https://github.com/getbible/v2) query will look like this:

    https://getbible.net/v2/kjv/62/3.json
```

**Comment by Metanoia23** [comment]
Ah ok, da gibt es schon einen Pull-Request dafür:
https://github.com/renehamburger/blinx.js/pull/58

👍

**Comment by renehamburger** [comment]
Danke für die Erinnerung, Manuel! Mir hatte dafür die Zeit gefehlt, aber ich schau es mir jetzt direkt noch mal an.

Hast du generell Interesse, bei diesem Projekt mitzuwirken? Hast du Erfahrung mit JavaScript oder TypeScript?

**Comment by Metanoia23** [comment]
Super, Danke! 

Prinzipiell programmieren kann ich es schon, hab aber jetzt vor allem Erfahrung mit Backend-Entwicklung. Ich arbeite ehrenamtlich an einem [Projekt](https://crossload.org/), da haben wir auch Frontend-Entwickler. Aber die haben jetzt auch nicht so viel freie Zeit 😅

**Comment by renehamburger** [comment]
Starkes Projekt!

Ihr solltet mal testen, ob blinx.js eure Bibelstellen besser erfasst:

![image](https://user-images.githubusercontent.com/4340524/164749433-d9b778e2-e322-4c85-a2f2-86707573c841.png)

Ist das der Grund, warum du hier gelandet bist?

Gib die Frage, ob einer eurer Front-End-Entwickler Lust hat, hier mit einzusteigen, gerne weiter.

**Comment by Metanoia23** [comment]
Alles klar, gebe ich gerne mal weiter. Ähem, wir nutzen schon blinx.js, deshalb bin ich hier gelandet 😉 Ist leicht angepasst.
Übrigens ist mir noch aufgefallen, dass Bibelbücher mit einem Kapitel zum Beispiel `Judas 1` nicht gefunden wird, nur `Judas 1,1`. Aber `Judas 2` geht wieder.

**Comment by Metanoia23** [comment]
> Ihr solltet mal testen, ob blinx.js eure Bibelstellen besser erfasst

Also wir haben blinx.js noch nicht so lange und unsere Redakteure kommen auch nicht immer gleich hinterher. In dieser Mitschrift aus deinem Screenshot waren einige Bibelstellenangaben nicht sauber formatiert/angegeben. Ich hab das mal [korrigiert](https://crossload.org/inhalte/b9FHG7VW0P/Gott-ist-nicht-stur-J%C3%BCrg-Birnstiel). 
Wir haben übrigens auch ein Redaktionsfrontend gebaut.

**Comment by Metanoia23** [comment]
Übrigens haben wir auch eine Kooperation mit Evangelium21 und werden demnächst einige Inhalte von dort importieren.

**Comment by renehamburger** [comment]
I'd better leave this open for now. This will be resolved in #58.

**Comment by renehamburger** [comment]
> Also wir haben blinx.js noch nicht so lange und unsere Redakteure kommen auch nicht immer gleich hinterher. In dieser Mitschrift aus deinem Screenshot waren einige Bibelstellenangaben nicht sauber formatiert/angegeben. Ich hab das mal [korrigiert](https://crossload.org/inhalte/b9FHG7VW0P/Gott-ist-nicht-stur-J%C3%BCrg-Birnstiel). Wir haben übrigens auch ein Redaktionsfrontend gebaut.

Eine Bibelstelle hattest du noch übersehen: "Jeremia 1, 1-20".

Jetzt sehe ich auch, warum ich nicht sofort erkannt habe, dass ihr blinx.js benutzt: ihr habt neben der farblichen Änderung des Popup-Footers auch die Quellenangaben "bxCredits" versteckt! Ich weiß gar nicht, was ich davon halten soll. Gerade den Link zu getBible, finde ich, sind wir dem Entwickler schuldig, weil er es auf eigene Kosten anbietet. Wie wäre es, wenn ihr blinx.js mit einem PR dahingegen ändert, dass die Credits hinter einem Symbol versteckt sind, z.B. `©`, das rechtsbündig im Footer angezeigt wird und das als Tooltip bei einem Hover diese Informationen anzeigt?

**Comment by Metanoia23** [comment]
Guten Morgen Rene, alles klar, wenn du es wichtig findest, nehmen wir die Credits wieder rein. Ich verstehe das natürlich, dass du auch viel Arbeit da rein gesteckt hast und das auch gewürdigt werden sollte. Der Gedanke war eben, dass das beim Betrachten von Gottes Wort sehr ablenkt, wenn immer dieser Schriftzug so prominent da steht, nicht um den Entwicklern die Anerkennung zu verweigern. Grundsätzlich eine gute Idee mit dem Copyright-Symbol, da müssen wir mal schauen, wie man es am besten macht.

**Comment by renehamburger** [comment]
> Der Gedanke war eben, dass das beim Betrachten von Gottes Wort sehr ablenkt, wenn immer dieser Schriftzug so prominent da steht, nicht um den Entwicklern die Anerkennung zu verweigern.

Ja, das kann ich sehr gut nachvollziehen! Daher werde ich das jetzt mal dezenter mit einen Copyright-Symbol machen. Könnte heute noch live gehen!

Mir ging es bei dem Schriftzug übrigens nur darum, mich bei getbible für ihre Arbeit und ihre kostenlose Bibel-API zu bedanken und zugleich etwas Werbung für blinx.js zu machen, damit Leute, die es auf einer Website sehen, auch einfach auf ihrer einbinden können. Ganz ohne den Schriftzug braucht es einen Entwickler, um herauszufinden, wo die Popups herkommen.

Könntest du mir vielleicht über https://www.bibel-fuer-alle.net/kontakt/ deine E-Mail-Adresse schicken, damit wir direkter kommunizieren können?

**Comment by renehamburger** [comment]
@Metanoia23, ab Version v0.4.9 sind die Copyright-Infos jetzt hinter einem klickbaren © versteckt. Ich werde dem jetzt noch schnell einen Abstandshalter geben und dem gesamten Popover einen Mindestbreite, dann sollte das gut passen.

Übrigens: falls ihr generell `, ` als Kapitel-Vers-Trennzeichen erlauben wollt und nicht nur `,` (also ohne Leerzeichen), dann wäre das schon möglich. Empfehlen würde ich das aber eher nicht, da es sonst zu Verwechselungen mit den Komma als Listenseparator führen kann.

Und noch eine ganz andere Sache: falls ihr irgendwann mal alle Bibelstellen eurer Artikel im Bibelstellenindex haben wolltet, dann könntet ihr blinx.js auch in eurem Back-end nutzen, um die Bibelestellen zu bestimmen, oder auch [blinx-cli](https://github.com/renehamburger/blinx-cli). blinx-cli ist ein sehr einfacher Crawler, der alle Bibelstellen einer Website bestimmt und ausgibt. Als erste Lösung kann das funktionieren, aber langfristig wäre es am besten, direkt über die Datenbank zu gehen.

**Comment by renehamburger** [comment]
I've just merged #58, which moves the getbible API to v2 and also improves loading & caching performance significantly!

**Comment by Metanoia23** [comment]
> @Metanoia23, ab Version v0.4.9 sind die Copyright-Infos jetzt hinter einem klickbaren © versteckt. Ich werde dem jetzt noch schnell einen Abstandshalter geben und dem gesamten Popover einen Mindestbreite, dann sollte das gut passen.
> 

Super, wir hätten einen Frontendler gehabt, der sich darum gekümmert hätte aber da warst du schneller. Herzlichen Dank für Deine Hilfe und schnelle Umsetzung!
